### ISSUE TITLE
Document all current Views

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#12]
Write Docs for all the controls currently available. You can find these [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Views). This might be too big to pick it up in one PR, by one person since the views might be quite extensive. Feel free to add a separate issue for a certain view and link it to this one.

I think personally I would rename this in the TOC to "User Interface" to also match the Forms Docs better.

- [x] AvatarView #19
- [x] CameraView #32
- [x] Expander (can be taken from [current Forms Docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/expander)) #14
- [ ] GravatarImageSource (note; this one is also in #9, might overlap, see where it fits best)
- [x] MediaElement (can be taken from [current Forms Docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/mediaelement)) #23
- [x] RangeSlider #39 
- [ ] [SideMenuView](https://github.com/xamarin/XamarinCommunityToolkit/pull/187)
- [ ] [SnackBar](https://github.com/xamarin/XamarinCommunityToolkit/pull/261)
- [x] [Shield](https://github.com/xamarin/XamarinCommunityToolkit/pull/338) #42
- [x] [BadgeView](https://github.com/xamarin/XamarinCommunityToolkit/pull/337/) #41 
- [x] [StateLayout](https://github.com/xamarin/XamarinCommunityToolkit/pull/450) #28 
- [x] [TabView](https://github.com/xamarin/XamarinCommunityToolkit/pull/525) #46
- [x] [DockLayout](https://github.com/xamarin/XamarinCommunityToolkit/pull/432) #43 
- [x] [UniformGrid](https://github.com/xamarin/XamarinCommunityToolkit/pull/619) #44
- [x] [LazyView](https://github.com/xamarin/XamarinCommunityToolkit/pull/796) #78 
- [ ] [Popups](https://github.com/xamarin/XamarinCommunityToolkit/pull/653)

**Comment by Cfun1** [comment]
@jfversluis since this issue is still open and gather all views could you add https://github.com/xamarin/XamarinCommunityToolkit/pull/796 LazyView to the task list ?

**Comment by Cfun1** [comment]
@jfversluis LazyView has been merged you may check it as done, could you please include Popup in the list?

**Comment by jfversluis** [comment]
Done

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
